DROP TABLE IF EXISTS motorista CASCADE;
DROP TABLE IF EXISTS passageiro CASCADE;
DROP TABLE IF EXISTS licenca_motorista CASCADE;
DROP TABLE IF EXISTS veiculo CASCADE;
DROP TABLE IF EXISTS corrida CASCADE;


CREATE TABLE motorista (
    id 				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  	nome 			VARCHAR(100) NOT NULL,
  	data_nascimento DATE NOT NULL,
	cpf				VARCHAR(11)	 NOT NULL,
	score			DOUBLE PRECISION,
	saldo			DECIMAL
);

ALTER TABLE motorista ADD CONSTRAINT pk_motorista PRIMARY KEY (id);
ALTER TABLE motorista ADD CONSTRAINT uk_motorista_cpf UNIQUE (cpf);


CREATE TABLE licenca_motorista (
	id 				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	numero			VARCHAR(11) NOT NULL,
	categoria 		VARCHAR(1) NOT NULL,
	data_vencimento	Date NOT NULL,
	motorista_id	BIGINT NOT NULL
);

ALTER TABLE licenca_motorista ADD CONSTRAINT pk_licenca_motorista PRIMARY KEY (id);
ALTER TABLE licenca_motorista ADD CONSTRAINT categoria_check CHECK (categoria IN ('A', 'B', 'C'));
ALTER TABLE licenca_motorista ADD CONSTRAINT fk_licenca_motorista_motorista FOREIGN KEY (motorista_id) REFERENCES  motorista;


CREATE TABLE passageiro (
    id 				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  	nome 			VARCHAR(100) NOT NULL,
  	data_nascimento DATE NOT NULL,
	cpf				VARCHAR(11)	 NOT NULL,
	score 			DOUBLE PRECISION,
	saldo			DECIMAL
);

ALTER TABLE passageiro ADD CONSTRAINT pk_passageiro PRIMARY KEY (id);
ALTER TABLE passageiro ADD CONSTRAINT uk_passageiro_cpf UNIQUE (cpf);


CREATE TABLE veiculo (
    id 				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  	placa 			VARCHAR(10)  NOT NULL,
  	modelo		 	VARCHAR(50)  NOT NULL,
	cor				VARCHAR(20)	 NOT NULL,
	foto			VARCHAR(255) NOT NULL,
	categoria 		VARCHAR(1)   NOT NULL,
	motorista_id	BIGINT       NOT NULL
);

ALTER TABLE veiculo ADD CONSTRAINT pk_veiculo PRIMARY KEY (id);
ALTER TABLE veiculo ADD CONSTRAINT categoria_check CHECK (categoria IN ('A', 'B', 'C'));
ALTER TABLE veiculo ADD CONSTRAINT fk_veiculo_motorista FOREIGN KEY (motorista_id) REFERENCES  motorista;


CREATE TABLE corrida (
	id 				BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	iniciox			DOUBLE PRECISION NOT NULL,
	inicioy			DOUBLE PRECISION NOT NULL,
	fimx			DOUBLE PRECISION NOT NULL,
	fimy			DOUBLE PRECISION NOT NULL,
	hora_inicio		TIMESTAMP,
	hora_chegada	TIMESTAMP,
	status			VARCHAR(20) NOT NULL,
	motorista_id	BIGINT NOT NULL,
	passageiro_id	BIGINT NOT NULL,
	score_motorista INT,
	score_passageiro INT
);

ALTER TABLE corrida ADD CONSTRAINT pk_corrida PRIMARY KEY (id);
ALTER TABLE corrida ADD CONSTRAINT status_check CHECK (status IN ('SOLICITADA', 'INICIADA', 'FINALIZADA'));
ALTER TABLE corrida ADD CONSTRAINT fk_corrida_motorista FOREIGN KEY (motorista_id) REFERENCES  motorista;
ALTER TABLE corrida ADD CONSTRAINT fk_corrida_passageiro FOREIGN KEY (passageiro_id) REFERENCES passageiro;
